version: '3.8'

services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4.2.2
    container_name: lutecio-lavalink
    restart: unless-stopped
    ports:
      - "2333:2333"
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
      - ./plugins:/opt/Lavalink/plugins
    environment:
      - _JAVA_OPTIONS=-Xmx4G

  bot:
    build: .
    container_name: lutecio-bot
    restart: unless-stopped
    depends_on:
      - lavalink
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}